config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id]) # return restaurant based on id
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
     # localhost:3000/restaurant/11
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
     # localhost:3000/restaurant/11
  end

  def destroy
    @restaurant = restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurant_path(@restaurant), status: :see_other
     # localhost:3000/restaurants
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # We need @restaurant in our `simple_form_for`
  before_action :set_restaurant, only: %i[new create]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
    redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_restaurant.html.erb
<%= simple_form_for model: @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Restaurants</h1>
<%= render "restaurant", restaurant: @restaurant %>
    <%# <p>
      <%= link_to "Show this restaurant", restaurant %>
    <%# </p> %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<%# <%= render "restaurant", restaurant: @restaurant %> %>
 <div class="listRestaurant">
    <ul>
      <% @restaurants.each do |restaurant| %>
      <li class="restaurants"><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
      <% end %>
    </ul>
      <%= link_to "Create a Restaurant", new_restaurant_path, class: "btn btn-primary"%>
  </div>

app/views/restaurants/new.html.erb
<h1>Restaurants</h1>
<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render restaurants %>
    <%# <p>
      <%= link_to "Show this restaurant", restaurant %>
    <%# </p> %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.rating %></p>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%# <%= simple_form_for [@restaurant, @review] do |f| %>
  <%# <%= f.input :content %>
  <%# <%= f.submit "Submit review", class: "btn btn-primary" %>
<%# <% end %>
<%= render "restaurant", restaurant: @restaurant %>
  <%# <%= f.label :rating %>
  <%# <%= f.number_field :rating %> 